### ISSUE TITLE
question

### ISSUE THREAD

**Issue by JacProsser** [fakeshadow/pxs-psn-api#7]
are you able to delete psn friends with this?

**Comment by fakeshadow** [comment]
I'm not aware there is an API for it so I guess no you can't.

**Comment by JacProsser** [comment]
ah right just need to delete my whole friends list cause i can't be bothered to do it manually

**Comment by JacProsser** [comment]
if you find anything would you be able to contact me or update this repo to show the details on it?

**Comment by fakeshadow** [comment]
no problem. Would @ you if I can find an API to do that.

**Comment by JacProsser** [comment]
thank you
